name: Build APK Only

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Bump version and push
        run: |
          npm version patch --no-git-tag-version
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Bot"
          git add package.json package-lock.json
          git commit -m "chore: bump version [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build APK
        run: eas build --platform android --non-interactive --output=./builds

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: ./builds/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}