name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      APP_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Bump version in package.json
        run: |
          npm version patch --no-git-tag-version
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Bot"
          git add package.json package-lock.json
          git commit -m "chore: bump version [skip ci]" || echo "No changes to commit"

      - name: Push version bump
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          npm install -g expo-cli
          # expo build:android --non-interactive --no-wait

      - name: Archive source code for deploy
        run: tar --exclude='.git' --exclude='source.tar.gz' -czf source.tar.gz ./*

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          source: "source.tar.gz"
          target: ${{ secrets.VDS_PATH }}

      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.VDS_KEY }}
          script: |
            cd ${{ secrets.VDS_PATH }}
            tar xzf source.tar.gz
            docker build -t ${{ github.event.repository.name }}:latest .
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker run -d --name ${{ github.event.repository.name }} -p 8085:8085 ${{ github.event.repository.name }}:latest